citiesArray = [
    "Rostock",
    "Berlin",
    "Dresden",
    "Leipzig",
    "Magdeburg",
    "Lübeck",
    "Braunschweig",
    "Hannover",
    "Hamburg",
    "Bremen",
    "Munster",
    "Köln",
    "Düsseldorf",
    "München", 
    "Ulm",
    "Ingolstadt",
    "Stuttgart",
    "Baden",
    "Frankfurt",
    "Nürnberg",
    "Mainz",
    "Trier",
    "Bonn",
]

citiesRoutes = {
   "Rostock": ["Berlin", "Magdeburg", "Lübeck"],
   "Berlin": ["Rostock", "Magdeburg", "Dresden"],
   "Dresden": ["Berlin", "Leipzig"],
   "Leipzig": ["Dresden", "Magdeburg", "Nürnberg"],
   "Magdeburg": ["Rostock", "Berlin", "Leipzig", "Braunschweig", "Lübeck"],
   "Lübeck": ["Rostock", "Magdeburg", "Braunschweig", "Hannover", "Hamburg"],
   "Braunschweig": ["Lübeck", "Magdeburg", "Nürnberg", "Mainz", "Düsseldorf", "Munster", "Hannover"],
   "Hannover": ["Lübeck", "Braunschweig", "Munster", "Bremen", "Hamburg"],
   "Hamburg": ["Lübeck", "Hannover", "Bremen"],
   "Bremen": ["Hamburg", "Hannover", "Munster"],
   "Munster": ["Bremen", "Hannover", "Braunschweig", "Düsseldorf", "Köln"],
   "Köln":["Düsseldorf","Bonn","Munster" ],
   "Düsseldorf":["Munster","Köln","Mainz","Braunschweig"],
   "München":["Ulm","Ingolstadt"],
   "Ulm":["Ingolstadt","München","Stuttgart"],
   "Ingolstadt":["Ulm","München","Stuttgart","Nürnberg"],
   "Stuttgart":["Frankfurt","Baden","Ulm","Ingolstadt"],
   "Baden":[ "Frankfurt","Stuttgart"],
   "Frankfurt":["Nürnberg","Mainz","Trier","Baden","Stuttgart"],
   "Nürnberg": ["Frankfurt", "Ingolstadt","Leipzig","Braunschweig","Mainz" ],
   "Mainz": ["Frankfurt","Trier","Nürnberg","Braunschweig","Düsseldorf","Köln","Bonn" ],
   "Trier": ["Bonn","Frankfurt","Mainz"],
   "Bonn":["Trier","Mainz","Köln" ],
}

citiesDistances: {
    "Rostock": [
        {"Rostock": 0}, {"Berlin": 250}, {"Dresden": 436}, {"Leipzig": 400}, {"Magdeburg": 295}, {"Lübeck": 120}, {"Braunschweig": 291},
        {"Hannover": 327}, {"Hamburg": 184}, {"Bremen": 301}, {"Munster": 458}, {"Köln": 601}, {"Düsseldorf": 577}, {"München": 793}, {"Ulm": 831},
        {"Ingolstadt": 718}, {"Stuttgart": 831}, {"Baden": 801}, {"Frankfurt": 668}, {"Nürnberg": 648}, {"Mainz": 697}, {"Trier": 762},{"Bonn": 627},
        ],
    "Berlin": [
        {"Rostock": 250}, {"Berlin": 0}, {"Dresden": 193}, {"Leipzig": 190}, {"Magdeburg": 156}, {"Lübeck": 280}, {"Braunschweig": 235},
        {"Hannover": 286}, {"Hamburg": 286}, {"Bremen": 394}, {"Munster": 474}, {"Köln": 573}, {"Düsseldorf": 564}, {"München": 584}, {"Ulm": 622},
        {"Ingolstadt": 509}, {"Stuttgart": 628}, {"Baden": 678}, {"Frankfurt": 545}, {"Nürnberg": 439}, {"Mainz": 574}, {"Trier": 719},{"Bonn": 600},
        ],
    "Dresden": [
        {"Rostock": 436}, {"Berlin": 193}, {"Dresden": 0}, {"Leipzig": 112}, {"Magdeburg": 227}, {"Lübeck": 471}, {"Braunschweig": 314},
        {"Hannover": 312}, {"Hamburg": 377}, {"Bremen": 404}, {"Munster": 435}, {"Köln": 474}, {"Düsseldorf": 485}, {"München": 359}, {"Ulm": 398},
        {"Ingolstadt": 303}, {"Stuttgart": 412}, {"Baden": 442}, {"Frankfurt": 372}, {"Nürnberg": 259}, {"Mainz": 403}, {"Trier": 522},{"Bonn": 466},
        ],
    "Leipzig": [
        {"Rostock": 400}, {"Berlin": 190}, {"Dresden": 112}, {"Leipzig": 0}, {"Magdeburg": 101}, {"Lübeck": 303}, {"Braunschweig": 163},
        {"Hannover": 214}, {"Hamburg": 294}, {"Bremen": 310}, {"Munster": 335}, {"Köln": 380}, {"Düsseldorf": 389}, {"München": 360}, {"Ulm": 369},
        {"Ingolstadt": 294}, {"Stuttgart": 264}, {"Baden": 383}, {"Frankfurt": 293}, {"Nürnberg": 229}, {"Mainz": 325}, {"Trier": 441},{"Bonn": 375},
        ],
    "Magdeburg": [
        {"Rostock": 295}, {"Berlin": 156}, {"Dresden": 227}, {"Leipzig": 101}, {"Magdeburg": 0}, {"Lübeck": 203}, {"Braunschweig": 77},
        {"Hannover": 132}, {"Hamburg": 280}, {"Bremen": 217}, {"Munster": 276}, {"Köln": 350}, {"Düsseldorf": 350}, {"München": 444}, {"Ulm": 431},
        {"Ingolstadt": 375}, {"Stuttgart": 411}, {"Baden": 415}, {"Frankfurt": 304}, {"Nürnberg": 300}, {"Mainz": 334}, {"Trier": 600},{"Bonn": 351},
        ],
    "Lübeck": [
        {"Rostock": 120}, {"Berlin": 280}, {"Dresden": 471}, {"Leipzig": 303}, {"Magdeburg": 203}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 650},{"Bonn": 426},
        ],
    "Braunschweig": [
        {"Rostock": 291}, {"Berlin": 235}, {"Dresden": 314}, {"Leipzig": 163}, {"Magdeburg": 77}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 389},{"Bonn": 292},
        ],
    "Hannover": [
        {"Rostock": 327}, {"Berlin": 286}, {"Dresden": 312}, {"Leipzig": 214}, {"Magdeburg": 132}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 362},{"Bonn": 258},
        ],
    "Hamburg": [
        {"Rostock": 184}, {"Berlin": 286}, {"Dresden": 377}, {"Leipzig": 294}, {"Magdeburg": 280}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 481},{"Bonn": 371},
        ],
    "Bremen": [
        {"Rostock": 301}, {"Berlin": 394}, {"Dresden": 404}, {"Leipzig": 310}, {"Magdeburg": 217}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 399},{"Bonn": 286},
        ],
    "Munster": [
        {"Rostock": 458}, {"Berlin": 474}, {"Dresden": 435}, {"Leipzig": 335}, {"Magdeburg": 276}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 253},{"Bonn": 142},
        ],
    "Köln": [
        {"Rostock": 601}, {"Berlin": 573}, {"Dresden": 573}, {"Leipzig": 380}, {"Magdeburg": 350}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 134},{"Bonn": 25},
        ],
    "Düsseldorf": [
        {"Rostock": 577}, {"Berlin": 564}, {"Dresden": 564}, {"Leipzig": 389}, {"Magdeburg": 350}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 164},{"Bonn": 59},
        ],
    "München": [
        {"Rostock": 793}, {"Berlin": 584}, {"Dresden": 359}, {"Leipzig": 360}, {"Magdeburg": 444}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 402},{"Bonn": 434},
        ], 
    "Ulm": [
        {"Rostock": 831}, {"Berlin": 622}, {"Dresden": 398}, {"Leipzig": 369}, {"Magdeburg": 431}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 287},{"Bonn": 333},
        ],
    "Ingolstadt": [
        {"Rostock": 718}, {"Berlin": 509}, {"Dresden": 303}, {"Leipzig": 294}, {"Magdeburg": 375}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 364},{"Bonn": 380},
        ],
    "Stuttgart": [
        {"Rostock": 831}, {"Berlin": 628}, {"Dresden": 412}, {"Leipzig": 264}, {"Magdeburg": 411}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 213},{"Bonn": 264},
        ],
    "Baden": [
        {"Rostock": 801}, {"Berlin": 678}, {"Dresden": 442}, {"Leipzig": 383}, {"Magdeburg": 415}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 152},{"Bonn": 213},
        ],
    "Frankfurt": [
        {"Rostock": 668}, {"Berlin": 545}, {"Dresden": 372}, {"Leipzig": 293}, {"Magdeburg": 304}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 150},{"Bonn": 130},
        ],
    "Nürnberg": [
        {"Rostock": 648}, {"Berlin": 439}, {"Dresden": 259}, {"Leipzig": 229}, {"Magdeburg": 300}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 321},{"Bonn": 318},
        ],
    "Mainz": [
        {"Rostock": 697}, {"Berlin": 574}, {"Dresden": 403}, {"Leipzig": 325}, {"Magdeburg": 334}, {"Lübeck": 0}, {"Braunschweig": 0},
        {"Hannover": 0}, {"Hamburg": 0}, {"Bremen": 0}, {"Munster": 0}, {"Köln": 0}, {"Düsseldorf": 0}, {"München": 0}, {"Ulm": 0},
        {"Ingolstadt": 0}, {"Stuttgart": 0}, {"Baden": 0}, {"Frankfurt": 0}, {"Nürnberg": 0}, {"Mainz": 0}, {"Trier": 119},{"Bonn": 117},
        ],
    "Trier": [
        {"Rostock": 762}, {"Berlin": 719}, {"Dresden": 522}, {"Leipzig": 441}, {"Magdeburg": 600}, {"Lübeck": 650}, {"Braunschweig": 389},
        {"Hannover": 362}, {"Hamburg": 481}, {"Bremen": 399}, {"Munster": 253}, {"Köln": 134}, {"Düsseldorf": 164}, {"München": 402}, {"Ulm": 287},
        {"Ingolstadt": 364}, {"Stuttgart": 213}, {"Baden": 152}, {"Frankfurt": 150}, {"Nürnberg": 321}, {"Mainz": 119}, {"Trier": 0},{"Bonn": 113},
        ],
    "Bonn": [
        {"Rostock": 627}, {"Berlin": 600}, {"Dresden": 466}, {"Leipzig": 375}, {"Magdeburg": 351}, {"Lübeck": 426}, {"Braunschweig": 292},
        {"Hannover": 258}, {"Hamburg": 371}, {"Bremen": 286}, {"Munster": 142}, {"Köln": 25}, {"Düsseldorf": 59}, {"München": 434}, {"Ulm": 333},
        {"Ingolstadt": 380}, {"Stuttgart": 264}, {"Baden": 213}, {"Frankfurt": 130}, {"Nürnberg": 318}, {"Mainz": 117}, {"Trier": 113},{"Bonn": 0},
        ],
}
